const $=id=>document.getElementById(id);const micBtn=$('micBtn'),state=$('state'),transcript=$('transcript'),response=$('response'),clearBtn=$('clearBtn'),historyBtn=$('historyBtn'),historyPanel=$('historyPanel'),settingsPanel=$('settingsPanel'),historyList=$('historyList'),voiceToggle=$('voiceToggle'),langSelect=$('langSelect'),statusText=$('statusText');
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null,history=JSON.parse(localStorage.getItem('vantavoice-history')||'[]');
function saveHistory(q,r){history.unshift({q,r,t:new Date().toLocaleString()});history=history.slice(0,30);localStorage.setItem('vantavoice-history',JSON.stringify(history));renderHistory()}
function renderHistory(){historyList.innerHTML=history.length?history.map(x=>`<div class="history-item"><b>${escapeHtml(x.q)}</b><span>${escapeHtml(x.r)}</span><small>${x.t}</small></div>`).join(''):'No conversations yet.'}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function speak(text){if(!voiceToggle.checked||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=langSelect.value;u.rate=.98;u.pitch=1;speechSynthesis.speak(u)}
function answer(text){const q=text.toLowerCase().trim();const now=new Date();let r;if(q.includes('time'))r=`It is ${now.toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}.`;else if(q.includes('date')||q.includes('today'))r=`Today is ${now.toLocaleDateString([], {weekday:'long',month:'long',day:'numeric',year:'numeric'})}.`;else if(q.includes('joke'))r='Why do programmers prefer dark mode? Because light attracts bugs.';else if(q.includes('setting')){settingsPanel.classList.toggle('show');r='Settings panel toggled.';}else if(/hello|hi|hey/.test(q))r='Hey! VantaVoice is listening.';else r=`I heard: “${text}”. VantaVoice is ready for Gemini-powered responses when a secure backend is connected.`;response.textContent=r;saveHistory(text,r);speak(r)}
function start(){if(!recognition)return;try{recognition.lang=langSelect.value;recognition.start()}catch(e){}}
if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang='en-IN';recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{micBtn.classList.add('active');state.textContent='Listening… speak now';statusText.textContent='Listening'};recognition.onend=()=>{micBtn.classList.remove('active');state.textContent='Tap the microphone to speak';statusText.textContent='System ready'};recognition.onerror=e=>{micBtn.classList.remove('active');state.textContent=e.error==='not-allowed'?'Microphone permission blocked':'Voice input error — try again';statusText.textContent='Microphone unavailable'};recognition.onresult=e=>{let finalText='',interim='';for(let i=e.resultIndex;i<e.results.length;i++)e.results[i].isFinal?finalText+=e.results[i][0].transcript:interim+=e.results[i][0].transcript;transcript.textContent=finalText||interim;if(finalText)answer(finalText)}}else{micBtn.disabled=true;state.textContent='Speech recognition is not supported in this browser'}
micBtn.onclick=start;clearBtn.onclick=()=>{transcript.textContent='Your words will appear here…';response.textContent=''};historyBtn.onclick=()=>historyPanel.classList.toggle('show');$('settingsPanel').onclick=e=>e.stopPropagation();document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{transcript.textContent=b.dataset.command;answer(b.dataset.command)});langSelect.onchange=()=>{if(recognition)recognition.lang=langSelect.value};renderHistory();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
