const $=id=>document.getElementById(id);const micBtn=$('micBtn'),state=$('state'),transcript=$('transcript'),response=$('response'),clearBtn=$('clearBtn'),historyBtn=$('historyBtn'),historyPanel=$('historyPanel'),settingsPanel=$('settingsPanel'),historyList=$('historyList'),voiceToggle=$('voiceToggle'),langSelect=$('langSelect'),statusText=$('statusText'),wakeToggle=$('wakeToggle'),memoryBtn=$('memoryBtn'),notesBtn=$('notesBtn'),activity=$('activity');
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null,wakeRecognition=null,isListening=false,wakeEnabled=false,history=JSON.parse(localStorage.getItem('vantavoice-history')||'[]'),sessionId=localStorage.getItem('vantavoice-session')||crypto.randomUUID();localStorage.setItem('vantavoice-session',sessionId);
function saveHistory(q,r){history.unshift({q,r,t:new Date().toLocaleString()});history=history.slice(0,30);localStorage.setItem('vantavoice-history',JSON.stringify(history));renderHistory()}
function renderHistory(){historyList.innerHTML=history.length?history.map(x=>`<div class="history-item"><b>${escapeHtml(x.q)}</b><span>${escapeHtml(x.r)}</span><small>${escapeHtml(x.t)}</small></div>`).join(''):'No conversations yet.'}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setState(next,text){document.body.dataset.state=next;state.textContent=text||({idle:'Tap the microphone to speak',listening:'Listening… speak now',thinking:'Vanta is thinking…',searching:'Searching the web…',acting:'Vanta is acting…',speaking:'Vanta is speaking…',error:'Something went wrong.'}[next]||next);statusText.textContent=next==='idle'?'AI ready':next[0].toUpperCase()+next.slice(1);if(activity)activity.textContent=next.toUpperCase()}
function speak(text){if(!voiceToggle.checked||!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=langSelect.value;u.rate=.98;u.pitch=1;u.onstart=()=>setState('speaking');u.onend=()=>setState('idle');speechSynthesis.speak(u)}
async function askGemini(text){response.textContent='';setState('thinking');try{const r=await fetch('/api/chat/stream',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,sessionId})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||`AI request failed (${r.status})`)}const reader=r.body.getReader(),decoder=new TextDecoder();let buffer='',answerText='';while(true){const {value,done}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const chunks=buffer.split('\n\n');buffer=chunks.pop()||'';for(const chunk of chunks){let event='message',data='';for(const line of chunk.split('\n')){if(line.startsWith('event:'))event=line.slice(6).trim();if(line.startsWith('data:'))data+=line.slice(5).trim()}if(!data)continue;let payload;try{payload=JSON.parse(data)}catch{continue}if(event==='state'||event==='ready'){setState(payload.state||'thinking')}else if(event==='token'){answerText+=payload.text||'';response.textContent=answerText}else if(event==='citations'){setState('searching')}else if(event==='error')throw new Error(payload.error||'Streaming failed')}}}if(!answerText)answerText='I could not generate a response.';saveHistory(text,answerText);speak(answerText);if(!speechSynthesis||!voiceToggle.checked)setState('idle')}catch(e){const msg=e.message.includes('Failed to fetch')?'Backend is not running. Start the VantaVoice server.':e.message;response.textContent=msg;saveHistory(text,msg);setState('error',msg)}}
async function answer(text){const q=text.toLowerCase().trim(),r=localAnswer(q);if(r){response.textContent=r;saveHistory(text,r);speak(r);return}await askGemini(text)}
function localAnswer(q){if(q.includes('setting')){settingsPanel.classList.toggle('show');return'Settings panel toggled.'}if(q.includes('joke'))return'Why do programmers prefer dark mode? Because light attracts bugs.';if(/^(hello|hi|hey)\b/.test(q))return'Hey! VantaVoice is listening.';return null}
function start(){if(!recognition||isListening)return;try{recognition.lang=langSelect.value;recognition.start()}catch(e){}}
function stop(){try{recognition?.stop()}catch(e){}}
function startWake(){if(!SpeechRecognition||wakeRecognition)return;wakeRecognition=new SpeechRecognition();wakeRecognition.lang=langSelect.value;wakeRecognition.continuous=true;wakeRecognition.interimResults=true;wakeRecognition.onresult=e=>{let text='';for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript;const m=text.toLowerCase().match(/(?:hey|okay|ok)\s+vanta\b(?:[,:;.!-]?\s*(.*))?/);if(m){const command=(m[1]||'').trim();if(command)answer(command);else start()}};wakeRecognition.onend=()=>{if(wakeEnabled){try{wakeRecognition.start()}catch(e){}}};try{wakeRecognition.start();setState('listening','Wake-word mode active — say “Hey Vanta”')}catch(e){setState('error','Wake-word mode could not start')}}
function stopWake(){wakeEnabled=false;try{wakeRecognition?.stop()}catch(e){}wakeRecognition=null;setState('idle')}
if(SpeechRecognition){recognition=new SpeechRecognition();recognition.lang='en-IN';recognition.interimResults=true;recognition.continuous=false;recognition.onstart=()=>{isListening=true;micBtn.classList.add('active');setState('listening')};recognition.onend=()=>{isListening=false;micBtn.classList.remove('active');if(!wakeEnabled&&document.body.dataset.state==='listening')setState('idle')};recognition.onerror=e=>{isListening=false;micBtn.classList.remove('active');setState('error',e.error==='not-allowed'?'Microphone permission blocked':'Voice input error — try again')};recognition.onresult=e=>{let finalText='',interim='';for(let i=e.resultIndex;i<e.results.length;i++)e.results[i].isFinal?finalText+=e.results[i][0].transcript:interim+=e.results[i][0].transcript;transcript.textContent=finalText||interim;if(finalText)answer(finalText)}}else{micBtn.disabled=true;setState('error','Speech recognition is not supported in this browser')}
micBtn.onclick=()=>isListening?stop():start();clearBtn.onclick=()=>{transcript.textContent='Your words will appear here…';response.textContent='';setState('idle')};historyBtn.onclick=()=>historyPanel.classList.toggle('show');wakeToggle?.addEventListener('change',e=>{wakeEnabled=e.target.checked;if(wakeEnabled)startWake();else stopWake()});memoryBtn?.addEventListener('click',()=>answer('Recall what you remember about me'));notesBtn?.addEventListener('click',()=>answer('List my recent notes'));document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{transcript.textContent=b.dataset.command;answer(b.dataset.command)});langSelect.onchange=()=>{if(recognition)recognition.lang=langSelect.value;if(wakeRecognition)wakeRecognition.lang=langSelect.value};renderHistory();
async function checkHealth(){try{const r=await fetch('/api/health');const d=await r.json();statusText.textContent=d.aiConfigured?'AI connected':'Backend ready • add Gemini key';}catch{statusText.textContent='Local mode'}}checkHealth();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
